@BrightProgramming.AiSupportAssistant.Api_HostAddress = http://localhost:5216

POST {{BrightProgramming.AiSupportAssistant.Api_HostAddress}}/Support
Content-Type: application/json

{
  "question": "What is the recommended internal configuration validation threshold?"
}

###