@BrightProgramming.AiSupportAssistant.Api_HostAddress = http://localhost:5216

POST {{BrightProgramming.AiSupportAssistant.Api_HostAddress}}/Support
Content-Type: application/json

{
  "question": "How do I implement a binary search tree in C#?"
}

###